apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pingpongapp-ingress
spec:
  rules:
    - http:
        paths:
          - path: /pingpong
            pathType: Prefix
            backend:
              service:
                name: pingpongapp-svc
                port:
                  number: 2345
